# The difference between Tensorflow  & Keras
Tensorflow與Keras最大的差別是 Tensorflow必須要自行設計tensor(矩陣)運算  
 * Keras是在Tensorflow之上的高階API 提供了更簡潔和方便 適合初學者和快速開發    
 * Tensorflow有更強的可擴展性 可以更容易地制定每個模型的每個組件 因此更適合研究項目和生產級別的模型     

可以使用Tensorflow提供的model建立計算圖 自己設計張量運算流程 並建構Deep learning model、machine learning model  


# 建立計算圖

In [2]:
print(tf.__version__)

2.16.1


# 建立計算圖

tf變數類型主要有三種:`tf.constant` `tf.Variable` `tf.placeholder`   
 * tf.constant:他就是一個constant的類別 可以放入各種資料型態 做一些基礎運算 也可以接受python list、numpy作為輸入 並將其轉換為tensor 
 * tf.Variable:放置可學習的變數or可求導的變數  
 * tf.placeholder:給定長度或著資料格式先佔有一個空間 不需要給定初始值 但是TF2.0後已經不使用這個變數了  

In [3]:
# 用於啟用類似TF1.x建構的code
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

ts_c = tf.constant(2, name = 'ts_c')
print(ts_c)

ts_x = tf.Variable(ts_c + 5, name='ts_x')
print(ts_x)


Instructions for updating:
non-resource variables are not supported in the long term
Tensor("ts_c:0", shape=(), dtype=int32)
<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>


eval()取得tensor's value

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
sess = tf.compat.v1.Session()

with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))
    print('ts_c=', ts_c.eval(session=sess))
    print('ts_x=', ts_x.eval(session=sess))

sess.close()



ts_c= 2
ts_x= 7
ts_c= 2
ts_x= 7


# Tensorflow placeholder

建立計算圖 一個tensor'area'= width * height

In [5]:
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area = tf.multiply(width, height)

使用placeholder時 需要通過`feed_dict`define parameters' value  
`feed_dict={width: 6, height: 8}`  

In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

with tf.compat.v1.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('area =', sess.run(area, feed_dict={width: 6, height: 8}))


area = 48


# TensorBoard

需要絕對位置:  
`tensorboard --logdir="D:\Project\Practical-Applications-of-Artificial-Intelligence\Machine Learning(ML)\log\area"`   
才找的到tensorflow board  
![tensorflow board](./images/Tensorflow%20board.png)

In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

width = tf.placeholder("int32", name='width')
height = tf.placeholder("int32", name='height')
area = tf.multiply(width, height, name='area')

tf.summary.scalar('area_summary', area)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width: 6, height: 8}))
    train_writer = tf.compat.v1.summary.FileWriter('log/area', sess.graph) # 視覺化 可在Tensorboard查看
    summary = sess.run(tf.compat.v1.summary.merge_all(), feed_dict={width: 6, height: 8})
    train_writer.add_summary(summary)


area= 48



In [9]:
ts_x = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_x)
    print(X)

[0.4 0.2 0.4]


In [10]:
print(X.shape)

(3,)


# Tensor
可以理解為[[0.4, 0.2, 0.4]] => 從最外拆掉一個[]就是 one-dimentional 拆掉第二個就是 two-dimentional  
所以是shape = (1, 3)

In [12]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)
    
print('shape:', X.shape)

[[0.4 0.2 0.4]]
shape: (1, 3)


In [16]:
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

print(W_array.shape)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]
(3, 2)


# Operations of Matrices
multiplication  
可以理解為 X為(1, 3)的matrix W為(3, 2)的matrix  => XW為(1, 2)的矩陣

                [-0.5, -0.2]
[1., 1., 1.] *  [-0.3,  0.4]
                [-0.5,  0.2]

In [18]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])
XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


addition

In [23]:
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = XW + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.1999999  0.6      ]]


In [24]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])

b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X, W) + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
