# The difference between Tensorflow  & Keras
Tensorflow與Keras最大的差別是 Tensorflow必須要自行設計tensor(矩陣)運算  
Keras是在Tensorflow之上的高階API 提供了更簡潔和方便  
Tensorflow是一個用於Nerual Network的的數學庫 

可以使用Tensorflow提供的model建立計算圖 自己設計張量運算流程 並建構Deep learning model、machine learning model

# 建立計算圖

In [2]:
print(tf.__version__)

2.16.1


# 建立計算圖

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

ts_c = tf.constant(2, name = 'ts_c')
print(ts_c)

ts_x = tf.Variable(ts_c + 5, name='ts_x')
print(ts_x)


Instructions for updating:
non-resource variables are not supported in the long term
Tensor("ts_c:0", shape=(), dtype=int32)
<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>


In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
sess = tf.compat.v1.Session()

with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))
    print('ts_c=', ts_c.eval(session=sess))
    print('ts_x=', ts_x.eval(session=sess))

sess.close()



ts_c= 2
ts_x= 7
ts_c= 2
ts_x= 7


# Tensorflow placeholder

建立計算圖

In [5]:
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area = tf.multiply(width, height)

執行

In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

with tf.compat.v1.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('area =', sess.run(area, feed_dict={width: 6, height: 8}))


area = 48


# TensorBoard

需要絕對位置:  
`tensorboard --logdir="D:\Project\Practical-Applications-of-Artificial-Intelligence\Machine Learning(ML)\log\area"`   
才找的到tensorflow board  
![tensorflow board](./images/Tensorflow%20board.png)

In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

width = tf.placeholder("int32", name='width')
height = tf.placeholder("int32", name='height')
area = tf.multiply(width, height, name='area')

# 将摘要操作添加到图中
tf.summary.scalar('area_summary', area)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width: 6, height: 8}))

    # 创建 FileWriter 对象来写入摘要数据
    train_writer = tf.compat.v1.summary.FileWriter('log/area', sess.graph)
    
    # 运行摘要操作，并将摘要数据写入日志文件
    summary = sess.run(tf.compat.v1.summary.merge_all(), feed_dict={width: 6, height: 8})
    train_writer.add_summary(summary)


area= 48



In [9]:
ts_x = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_x)
    print(X)

[0.4 0.2 0.4]


In [10]:
print(X.shape)

(3,)


In [12]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)
    
print('shape:', X.shape)

[[0.4 0.2 0.4]]
shape: (1, 3)


In [16]:
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

print(W_array.shape)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]
(3, 2)


# Operations of Matrices
multiplication

In [18]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])
XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


addition

In [23]:
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = XW + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.1999999  0.6      ]]


In [24]:
X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])

b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X, W) + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
